version: "3.7"
services:
  truffle:
    build: .
    container_name: truffle
    networks:
      - dev-net
    volumes:
      - ./:/home/app
      - ./abi:/home/app/abi
      - ./node_modules:/home/app/node_modules
    depends_on:
      - ganache
  app-ui:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: app-ui
    ports:
      - "3000:3000"
    networks:
      - dev-net
    volumes:
      - ./client:/home/app-ui
      - ./ganache_data:/ganache_data
      - ./abi:/home/app-ui/src/contracts
      - ./client/node_modules:/home/app-ui/node_modules
    depends_on:
      - ganache
      - truffle
  ganache:
    image: "trufflesuite/ganache-cli:latest"
    restart: unless-stopped
    networks:
      - dev-net
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
#      - --debug
      - --allowUnlimitedContractSize

volumes:
  abi:
networks:
  dev-net: